spring:
  mvc:
    cors:
      allowed-origins:
        - http://localhost:3000
        - http://your-other-domain.com
      allowed-methods: GET,POST,PUT,DELETE
      allowed-headers: "*"
      allow-credentials: true
